python oscar/run_captioning.py \
    --model_name_or_path models/pretrained_base/image_captioning/pretrained_base \
    --do_train \
    --train_yaml val.yaml --per_gpu_train_batch_size 3 \
    --do_lower_case \
    --add_od_labels \
    --learning_rate 3e-5 \
    --per_gpu_train_batch_size 64 \
    --num_train_epochs 60 \
    --tie_weights \
    --freeze_embedding \
    --label_smoothing 0.1 \
    --drop_worst_ratio 0.2 \
    --drop_worst_after 20000 \
    --output_dir output/